<a href="https://colab.research.google.com/github/doblepensador/Tests/blob/master/Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install scikit-surprise

     |████████████████████████████████| 11.8 MB 3.7 MB/s 
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.1-cp37-cp37m-linux_x86_64.whl size=1630178 sha256=d5e5f56f0cb90e1f2278fa1191c147e641457d1f7d77d6ee103a2febb877ac1d
  Stored in directory: /root/.cache/pip/wheels/76/44/74/b498c42be47b2406bd27994e16c5188e337c657025ab400c1c
Successfully built scikit-surprise


In [32]:
import numpy as np
from surprise import Dataset

In [33]:
data = Dataset.load_builtin('ml-100k', prompt = False)

***Content-based filtering ***

In [34]:
raw_data = np.array(data.raw_ratings, dtype=int) 
raw_data[:,0] -=1 #Make ID No. start from 0. 
raw_data[:,1] -=1 #Make Item No. start from 0.
raw_data

array([[      195,       241,         3, 881250949],
       [      185,       301,         3, 891717742],
       [       21,       376,         1, 878887116],
       ...,
       [      275,      1089,         1, 874795795],
       [       12,       224,         2, 882399156],
       [       11,       202,         3, 879959583]])

In [35]:
n_users = np.max(raw_data[:,0]) + 1
n_movies = np.max(raw_data[:,1]) + 1
shape = (n_users, n_movies)
shape


(943, 1682)

In [ ]:
adj_matrix = np.ndarray(shape, dtype=int)
for user_id, movie_id, rating, time in raw_data:
  adj_matrix[user_id][movie_id] = 1. 
  #Make an Adjacent Matrix for user & movie ID 
adj_matrix

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]])

In [36]:
my_id, my_vector = 0, adj_matrix[0]
best_match, best_match_id, best_match_vector = -1, -1, [] 
for user_id, user_vector in enumerate(adj_matrix):
  # Enumerating a 2-dimensional array makes it possible 
  # to iterate the first index and the remaining vector
  if user_id != my_id:
    similarity = np.dot(user_vector, my_vector)
    if similarity > best_match:
      best_match = similarity
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))

# >>> for r, row in enumerate(matrix):
# ...     for c, letter in enumerate(row):
# ...             print(r, c, letter)
# ...
# 0 0 A
# 0 1 B
# 0 2 C
# 1 0 D
# 1 1 E
# 1 2 F
# 2 0 G
# 2 1 H
# 2 2 I

the best match value is 2719. The best match ID is 275


In [ ]:
recommend_list = []
for i, log in enumerate(zip(my_vector, best_match_vector)):
  log1, log2 = log
  if log1 < 1. and log2 > 0.:
    recommend_list.append(i)
print(recommend_list)

# >>> numbers = [1, 2, 3]
# >>> letters = ["A", "B", "C"]
# >>> for pair in zip(numbers, letters):
# ...     print(pair)
# ...
# (1, 'A')
# (2, 'B')
# (3, 'C')

[272, 273, 275, 280, 281, 283, 287, 288, 289, 290, 292, 293, 297, 299, 300, 301, 302, 306, 312, 314, 315, 316, 317, 321, 322, 323, 324, 327, 330, 331, 332, 333, 339, 342, 345, 346, 353, 354, 355, 356, 357, 363, 364, 365, 366, 372, 374, 378, 379, 381, 382, 383, 384, 385, 386, 387, 390, 391, 392, 394, 395, 396, 398, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 412, 414, 416, 417, 418, 419, 420, 422, 424, 425, 426, 427, 428, 430, 431, 432, 435, 442, 446, 447, 448, 449, 450, 451, 452, 454, 455, 457, 460, 461, 462, 468, 469, 470, 471, 472, 473, 474, 478, 495, 500, 507, 517, 522, 525, 530, 539, 540, 543, 545, 546, 548, 549, 550, 551, 553, 557, 558, 560, 561, 562, 563, 565, 566, 567, 568, 570, 571, 574, 575, 576, 577, 580, 581, 582, 585, 587, 589, 590, 594, 596, 602, 623, 626, 627, 630, 633, 635, 639, 646, 648, 651, 652, 654, 657, 664, 668, 671, 677, 678, 681, 683, 684, 685, 690, 691, 692, 695, 696, 708, 709, 714, 718, 719, 720, 724, 726, 727, 731, 733, 734, 736, 738, 741, 742, 745,

In [ ]:
my_id, my_vector = 0, adj_matrix[0]
best_match, best_match_id, best_match_vector = 9999, -1, [] 
for user_id, user_vector in enumerate(adj_matrix):
  if user_id != my_id:
    euclidean_dist = np.sqrt(np.sum(np.square(my_vector - user_vector)))
    if euclidean_dist < best_match:
      best_match = euclidean_dist
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))

the best match value is 14.832396974191326. The best match ID is 737


In [ ]:
recommend_list = []
for i, log in enumerate(zip(my_vector, best_match_vector)):
  log1, log2 = log
  if log1 < 1. and log2 > 0.:
    recommend_list.append(i)
print(recommend_list)

[297, 312, 317, 342, 356, 366, 379, 384, 392, 402, 404, 407, 417, 422, 428, 433, 448, 454, 469, 473, 495, 510, 516, 526, 527, 549, 567, 602, 635, 649, 650, 654, 658, 661, 664, 696, 731, 746, 750, 754, 915, 918, 925, 929, 950, 968, 1015, 1046]


In [2]:
def compute_cos_similiarity(v1, v2):
  norm1 = np.sqrt(np.sum(np.square(v1)))
  norm2 = np.sqrt(np.sum(np.square(v2)))
  dot = np.dot(v1,v2)
  return dot/(norm1*norm2)


In [ ]:
my_id, my_vector = 0, adj_matrix[0]
best_match, best_match_id, best_match_vector = -1, -1, [] 
# The lowest value limit of a simple cosine function is "-1".
for user_id, user_vector in enumerate(adj_matrix):
  if user_id != my_id:
    cos_similarity = compute_cos_similiarity(my_vector, user_vector)
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))

the best match value is 0.5278586163659506. The best match ID is 915


In [ ]:
recommend_list = []
for i, log in enumerate(zip(my_vector, best_match_vector)):
  log1, log2 = log
  if log1 < 1. and log2 > 0.:
    recommend_list.append(i)
print(recommend_list)

[272, 275, 279, 280, 283, 285, 289, 294, 297, 316, 317, 355, 365, 366, 368, 379, 380, 381, 384, 386, 392, 398, 401, 404, 416, 420, 422, 424, 426, 427, 430, 432, 450, 460, 461, 466, 469, 471, 473, 474, 475, 479, 482, 483, 497, 505, 508, 510, 511, 522, 526, 527, 529, 530, 534, 536, 540, 545, 548, 549, 556, 557, 558, 560, 565, 567, 568, 569, 577, 580, 581, 582, 592, 596, 630, 635, 639, 641, 649, 651, 654, 673, 677, 678, 683, 684, 692, 696, 701, 703, 707, 708, 709, 712, 714, 719, 720, 726, 731, 734, 736, 738, 740, 745, 747, 754, 755, 761, 762, 763, 766, 780, 789, 791, 805, 819, 823, 824, 830, 843, 862, 865, 918, 929, 930, 938, 942, 943, 947, 958, 959, 960, 970, 977, 1004, 1008, 1009, 1010, 1013, 1041, 1045, 1069, 1072, 1073, 1078, 1097, 1100, 1108, 1112, 1118, 1134, 1193, 1205, 1207, 1216, 1219, 1267, 1334, 1400, 1427, 1596, 1681]


In [ ]:
adj_matrix = np.ndarray(shape, dtype=int)
for user_id, movie_id, ratings, time in raw_data:
  adj_matrix[user_id][movie_id] = ratings
adj_matrix

array([[5, 3, 4, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 5, 0, ..., 0, 0, 0]])

In [ ]:
my_id, my_vector = 0, adj_matrix[0]
best_match, best_match_id, best_match_vector = 9999, -1, [] 
for user_id, user_vector in enumerate(adj_matrix):
  if user_id != my_id:
    euclidean_dist = np.sqrt(np.sum(np.square(my_vector - user_vector)))
    if euclidean_dist < best_match:
      best_match = euclidean_dist
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))

the best match value is 55.06359959174482. The best match ID is 737


In [ ]:
my_id, my_vector = 0, adj_matrix[0]
best_match, best_match_id, best_match_vector = -1, -1, [] 
for user_id, user_vector in enumerate(adj_matrix):
  if user_id != my_id:
    cos_similarity = compute_cos_similiarity(my_vector, user_vector)
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))

the best match value is 0.569065731527988. The best match ID is 915


***Collaborative filtering ***
Taking similarity in both contents and users into account

In [ ]:
from surprise import KNNBasic, SVD, SVDpp, NMF
from surprise import Dataset
from surprise.model_selection import cross_validate

In [ ]:
data = Dataset.load_builtin('ml-100k', prompt = False)

In [ ]:
model = KNNBasic()
cross_validate(model, data, measures=['rmse', 'mae'], cv=5, n_jobs = 4, verbose= True)
# Root Mean Square Error(RMSE), Mean Absolute Error(MAE)
#n_jobs parameter can be used to distribute and exploit all the CPUs available in the local computer.

Evaluating RMSE, MAE of algorithm KNNBasic on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9806  0.9741  0.9768  0.9846  0.9732  0.9779  0.0042  
MAE (testset)     0.7736  0.7682  0.7724  0.7779  0.7697  0.7723  0.0034  
Fit time          0.36    0.50    0.69    0.66    0.35    0.51    0.14    
Test time         5.96    6.51    6.61    5.28    3.83    5.64    1.02    


{'fit_time': (0.35929393768310547,
  0.4950118064880371,
  0.6878383159637451,
  0.6633689403533936,
  0.35079169273376465),
 'test_mae': array([0.77357702, 0.76817901, 0.772427  , 0.7778605 , 0.76968265]),
 'test_rmse': array([0.98062048, 0.97406104, 0.97679807, 0.98459271, 0.97322377]),
 'test_time': (5.95732569694519,
  6.511231422424316,
  6.607081890106201,
  5.282946348190308,
  3.8317534923553467)}

In [ ]:
model = SVD()
cross_validate(model, data, measures=['rmse', 'mae'], cv=5, n_jobs = 4, verbose= True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9380  0.9345  0.9332  0.9419  0.9357  0.9367  0.0031  
MAE (testset)     0.7401  0.7354  0.7353  0.7424  0.7365  0.7379  0.0028  
Fit time          12.08   15.99   16.31   13.36   8.31    13.21   2.92    
Test time         0.75    0.53    0.41    0.27    0.18    0.43    0.20    


{'fit_time': (12.084012985229492,
  15.991334915161133,
  16.312626838684082,
  13.36305046081543,
  8.30781078338623),
 'test_mae': array([0.74010801, 0.73537773, 0.7353004 , 0.74240075, 0.73648617]),
 'test_rmse': array([0.9379747 , 0.93449967, 0.93319167, 0.94191635, 0.93572853]),
 'test_time': (0.7507827281951904,
  0.5320501327514648,
  0.41173458099365234,
  0.2689628601074219,
  0.1817939281463623)}

In [ ]:
model = NMF()
cross_validate(model, data, measures=['rmse', 'mae'], cv=5, n_jobs = 4, verbose= True)

Evaluating RMSE, MAE of algorithm NMF on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std     
RMSE (testset)    0.9605  0.9661  0.9612  0.9762  0.9541  0.9636  0.0074  
MAE (testset)     0.7579  0.7608  0.7563  0.7648  0.7488  0.7577  0.0053  
Fit time          13.63   15.57   16.09   13.34   8.78    13.48   2.58    
Test time         0.62    0.48    0.27    0.22    0.13    0.34    0.18    


{'fit_time': (13.625821113586426,
  15.56550121307373,
  16.09491801261902,
  13.344173669815063,
  8.775670051574707),
 'test_mae': array([0.75793043, 0.76078678, 0.75630993, 0.764832  , 0.74877719]),
 'test_rmse': array([0.96050237, 0.96610088, 0.96122116, 0.97620751, 0.95412024]),
 'test_time': (0.617149829864502,
  0.48038673400878906,
  0.26502037048339844,
  0.22306489944458008,
  0.13419532775878906)}

In [ ]:
# Takes too much time
model = SVDpp()
cross_validate(model, data, measures=['rmse', 'mae'], cv=5, n_jobs = 4, verbose= True)

***Hybrid filtering***

In [3]:
import numpy as np
from sklearn.decomposition import  randomized_svd, non_negative_factorization
from surprise import Dataset

In [4]:
data = Dataset.load_builtin('ml-100k', prompt=False)
raw_data = np.array(data.raw_ratings, dtype=int)
raw_data[:,0] -=1
raw_data[:,1] -=1
 

Trying to download dataset from http://files.grouplens.org/datasets/movielens/ml-100k.zip...
Done! Dataset ml-100k has been saved to /root/.surprise_data/ml-100k


In [5]:
n_user = np.max(raw_data[:,0])
n_movies = np.max(raw_data[:,1])
shape = (n_user+1, n_movies+1)
shape

(943, 1682)

In [6]:
adj_matrix = np.ndarray(shape, dtype=int)
for user_id, movie_id, rating, time in raw_data:
  adj_matrix[user_id][movie_id] = rating
adj_matrix

array([[5, 3, 4, ..., 0, 0, 0],
       [4, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [5, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 5, 0, ..., 0, 0, 0]])

In [7]:
U, S, V = randomized_svd(adj_matrix, n_components=2)
S = np.diag(S)

# SVD model allows us to decompose data into U and V matrix which are, in turn, scaled by S matrix. 

/usr/local/lib/python3.7/dist-packages/sklearn/utils/extmath.py:376: FutureWarning: If 'random_state' is not supplied, the current default is to use 0 as a fixed seed. This will change to  None in version 1.2 leading to non-deterministic results that better reflect nature of the randomized_svd solver. If you want to silence this warning, set 'random_state' to an integer seed or to None explicitly depending if you want your code to be deterministic or not.
  FutureWarning,


In [8]:
print(U.shape)
print(S.shape)
print(V.shape)

(943, 2)
(2, 2)
(2, 1682)


In [9]:
np.matmul(np.matmul(U,S),V)

array([[ 3.91732663e+00,  1.47276644e+00,  7.98261988e-01, ...,
         6.24907189e-04,  1.41100852e-02,  1.36545878e-02],
       [ 1.85777226e+00,  3.96191175e-01,  5.05705740e-01, ...,
         5.38862978e-03,  1.77237914e-03,  5.26968095e-04],
       [ 8.94989517e-01,  1.71578497e-01,  2.51738682e-01, ...,
         2.92094923e-03,  5.39937171e-04, -1.25733753e-04],
       ...,
       [ 9.92051955e-01,  2.10814957e-01,  2.70363365e-01, ...,
         2.89019297e-03,  9.34221962e-04,  2.66612193e-04],
       [ 1.30425401e+00,  5.27669941e-01,  2.50080165e-01, ...,
        -4.20677765e-04,  5.30525683e-03,  5.28069948e-03],
       [ 2.82999397e+00,  9.70812247e-01,  6.15871694e-01, ...,
         2.02091492e-03,  8.67740813e-03,  8.03107892e-03]])

In [10]:
# For SVD to be used
# Cosine similarity should be used.
my_id, my_vector = 0, U[0] # Based on the users' preference
best_match, best_match_id, best_match_vector = -1, -1, [] 
for user_id, user_vector in enumerate(U):
  if user_id != my_id:
    cos_similarity = compute_cos_similiarity(my_vector, user_vector)
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))
# Note that the predictability is way higher than that of content-based filtering alone. 

the best match value is 0.9999942295956324. The best match ID is 235


In [11]:
recommend_list = []
for i, log in enumerate(zip(adj_matrix[my_id], adj_matrix[best_match_id])):
  log1, log2 = log
  if log1 < 1. and log2 > 0.:
    recommend_list.append(i)
print(recommend_list)

[272, 273, 274, 281, 285, 288, 293, 297, 303, 306, 312, 317, 327, 332, 369, 410, 418, 419, 422, 426, 428, 431, 434, 442, 461, 475, 477, 482, 495, 503, 504, 505, 506, 509, 519, 520, 522, 525, 531, 545, 548, 590, 594, 595, 613, 631, 654, 658, 660, 672, 684, 685, 691, 695, 698, 704, 716, 728, 734, 749, 755, 863, 865, 933, 1012, 1038, 1101, 1327, 1400]


In [12]:
# Based on the contents' similarity 
# According to SVD, A=USV(transposed)
subj_movie_id, subj_movie_vector = 0, V.T[0] 
best_match, best_match_movie_id, best_match_movie_vector = -1, -1, [] 
for movie_id, movie_vector in enumerate(V.T):
  if movie_id != subj_movie_id:
    cos_similarity = compute_cos_similiarity(subj_movie_vector, movie_vector)
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_movie_id = movie_id
      best_match_movie_vector = movie_vector
print("the best match value is {0}. The best match movie ID is {1}".format(best_match, best_match_movie_id))
# Note that the predictability is way higher than that of content-based filtering alone. 

the best match value is 0.9999999951364144. The best match movie ID is 1287


In [13]:
# Non-negative factorization
A, B, iter = non_negative_factorization(adj_matrix, n_components=2)

/usr/local/lib/python3.7/dist-packages/sklearn/decomposition/_nmf.py:294: FutureWarning: The 'init' value, when 'init=None' and n_components is less than n_samples and n_features, will be changed from 'nndsvd' to 'nndsvda' in 1.1 (renaming of 0.26).
  FutureWarning,


In [16]:
np.matmul(A, B)

array([[3.71108858e+00, 1.48454102e+00, 7.39535363e-01, ...,
        3.64490531e-03, 1.45506510e-02, 1.44110916e-02],
       [2.11724416e+00, 2.37338725e-01, 5.51650703e-01, ...,
        4.76092332e-03, 3.03585167e-05, 0.00000000e+00],
       [9.85272360e-01, 1.10447010e-01, 2.56713988e-01, ...,
        2.21552443e-03, 1.41275191e-05, 0.00000000e+00],
       ...,
       [1.04485667e+00, 1.17126289e-01, 2.72238757e-01, ...,
        2.34950819e-03, 1.49818804e-05, 0.00000000e+00],
       [1.45758857e+00, 5.42112787e-01, 2.99181695e-01, ...,
        1.61177659e-03, 5.15921394e-03, 5.10771005e-03],
       [2.44733103e+00, 9.41208708e-01, 4.95740038e-01, ...,
        2.56992125e-03, 9.08287324e-03, 8.99389282e-03]])

In [20]:
# For NMF to be used
# Cosine similarity should be used.
my_id, my_vector = 0, A[0] # Based on the users' preference
best_match, best_match_id, best_match_vector = -1, -1, [] 
for user_id, user_vector in enumerate(A):
  if user_id != my_id:
    cos_similarity = compute_cos_similiarity(my_vector, user_vector)
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_id = user_id
      best_match_vector = user_vector
print("the best match value is {0}. The best match ID is {1}".format(best_match, best_match_id))
# Note that the predictability is way higher than that of content-based filtering alone. 

the best match value is 0.9999996856299355. The best match ID is 314


In [21]:
recommend_list = []
for i, log in enumerate(zip(adj_matrix[my_id], adj_matrix[best_match_id])):
  log1, log2 = log
  if log1 < 1. and log2 > 0.:
    recommend_list.append(i)
print(recommend_list)

[272, 275, 284, 285, 287, 300, 301, 302, 304, 317, 323, 326, 339, 381, 427, 430, 432, 460, 465, 474, 503, 507, 512, 519, 522, 530, 602, 641, 644, 650, 653, 656, 672, 708, 731, 740, 745, 769, 791, 1064, 1083]


In [22]:
# Based on the contents' similarity 
subj_movie_id, subj_movie_vector = 0, B.T[0] 
best_match, best_match_movie_id, best_match_movie_vector = -1, -1, [] 
for movie_id, movie_vector in enumerate(B.T):
  if movie_id != subj_movie_id:
    cos_similarity = compute_cos_similiarity(subj_movie_vector, movie_vector)
    if cos_similarity > best_match:
      best_match = cos_similarity
      best_match_movie_id = movie_id
      best_match_movie_vector = movie_vector
print("the best match value is {0}. The best match movie ID is {1}".format(best_match, best_match_movie_id))
# Note that the predictability is way higher than that of content-based filtering alone. 

the best match value is 0.9999999946284724. The best match movie ID is 255


In [28]:
similarity_dict = {}
for movie_id, movie_vector in enumerate(B.T):
  if movie_id != subj_movie_id:
    cos_similarity = compute_cos_similiarity(subj_movie_vector, movie_vector)
    similarity_dict[movie_id] = cos_similarity
print(similarity_dict)

# dicts = {}
# keys = range(4)
# values = ["Hi", "I", "am", "John"]
# for i in keys:
#     for x in values:
#         dicts[i] = x
# print(dicts)


{1: 0.7453992552836144, 2: 0.9778019553097885, 3: 0.6827993409644434, 4: 0.9582159410181996, 5: 0.9303449599849453, 6: 0.9989994557051917, 7: 0.6597615958256962, 8: 0.9999746859409137, 9: 0.8531365101128774, 10: 0.9021990949201407, 11: 0.8477585197241269, 12: 0.9905732563485712, 13: 0.9914173107475107, 14: 0.9790870598456294, 15: 0.9777289515993084, 16: 0.9660183473033935, 17: 0.5348293361424394, 18: 0.9553030672328775, 19: 0.9992471227160664, 20: 0.9583216007966082, 21: 0.7793141357546742, 22: 0.5348293361424393, 23: 0.9995945944769513, 24: 0.9918752434227344, 25: 0.6812155133522629, 26: 0.9168108804560079, 27: 0.6588322580561894, 28: 0.8302135774037839, 29: 0.5348293361424393, 30: 0.8198914620781742, 31: 0.5363483547829446, 32: 0.8237419055258377, 33: 0.9801272482548652, 34: 0.7552556615847066, 35: 0.9480644941964066, 36: 0.5348293361424393, 37: 0.9055889267773505, 38: 0.7370390310119986, 39: 0.730312180534811, 40: 0.9960939158513925, 41: 0.8098579917150313, 42: 0.8108567021792883, 4

In [39]:
sorted_values = sorted(similarity_dict.values(), reverse=True)
sorted_dict = {}

for i in sorted_values:
  for k in similarity_dict.keys():
    if similarity_dict[k] == i:
      sorted_dict[k] = similarity_dict[k]
      break

print(sorted_dict)

# dict1 = {1: 1, 2: 9, 3: 4}
# sorted_values = sorted(dict1.values()) # Sort the values
# sorted_dict = {}

# for i in sorted_values:
#     for k in dict1.keys():
#         if dict1[k] == i:
#             sorted_dict[k] = dict1[k]
#             break

# print(sorted_dict)

{255: 0.9999999946284724, 825: 0.999996696362232, 234: 0.999994127494346, 1439: 0.9999908580779233, 1654: 0.9999900720403069, 284: 0.9999881939621771, 668: 0.9999757298551666, 8: 0.9999746859409137, 1269: 0.9999704606476811, 458: 0.9999669039734406, 99: 0.9999514285064423, 104: 0.9999497251426883, 1516: 0.999932051427144, 454: 0.9999303597092621, 123: 0.9998858901457763, 1009: 0.9998841658880523, 1559: 0.9998079038994495, 1425: 0.9997828101337142, 340: 0.9997725452153517, 282: 0.9996870923467187, 1082: 0.9996320715846441, 1467: 0.9996094194941415, 23: 0.9995945944769513, 888: 0.9995632734451046, 221: 0.999554220358024, 148: 0.9994968872749529, 1287: 0.999495958224057, 1096: 0.9994421930481213, 921: 0.9993375429020385, 838: 0.9992995670393439, 19: 0.9992471227160664, 336: 0.9991353890399095, 411: 0.9990822721779552, 1320: 0.9990790411512179, 899: 0.9990762090963984, 951: 0.9990593449767724, 1537: 0.9990196553490953, 6: 0.9989994557051917, 1119: 0.9988311675093852, 313: 0.998683875782202